"""
    The purpose of this file is to provide the functions to do the following:
    - read in the provided data generated by the summarizers, scorer, and data display files
    - organize data in a format usable for pdf format
    - generate pdf of results and findings
"""